name: GaiaSmp
version: '${project.version}'
main: me.minignomer.gaiasmp.GaiaSmp
api-version: '1.20'
authors: [MiniGnomer]
commands:
  scroll:
    usage: /scroll <get/modify> <scroll_name/player_name>
    permission: gaiasmp.scroll
  gaiastone:
    usage: /gaiastone
    aliases:
      - forge
      - equip
    permission: gaiasmp.gaiastone
  level:
    usage: /level <player> <amount>
    permission: gaiasmp.level